### ISSUE TITLE
Enable output: 'export' for static site generation headless mode

### ISSUE THREAD

**Issue by gorm** [10up/headstartwp#694]
### Is your enhancement related to a problem? Please describe.

Not possible to deploy using static export. When I change nextConfig with output: '[export](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports)' it generates the following error:

`Error: ISR cannot be used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export`

### Describe alternatives you've considered

It would be great if this package could run with static site generation, so it would be possible to deploy static html, css, javascript and then run in headless mode with client side fetching without requiring node installed on the server.

Feedback is appreciated, if there is something I don't understand here. It was tested with the wp-nextjs template. Thanks for your eyes and time!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
You can export to a static site but as the error suggest you need to remove ISR (i.e the revalidate prop) from all routes since that's not supported for static exports.

To achieve what you want (fully static with client-side data fetching) you will also need to set https://github.com/10up/headstartwp/blob/develop/projects/wp-nextjs/src/pages/_app.js#L36 to true.

For context, most content-heavy sites will not need client-side data fetching since it's already fetched on the server. So the default template sets that to false.
